### ISSUE TITLE
The System.IO.IOException The process cannot access the file .net8

### ISSUE THREAD

**Issue by netwer** [lucaslorentz/minicover#172]
Hello, I would like to ask about some help and opened this issue to get some one.

I used this lib in my project with .net 6 fraemwork and everything works well.

But after update the .net version from` .net 6 to .net 8` and run the `minicover instrument` will get the following error:

`Unhandled exception. System.IO.IOException: The process cannot access the file 'MY_PROJECT_DLL.dll' because it is being used by another process.
   at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
   at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
   at MiniCover.Core.Instrumentation.Instrumenter.VisitAssemblyGroup(IInstrumentationContext context, InstrumentationResult result, IReadOnlyCollection1 assemblyFiles) in /src/MiniCover.Core/Instrumentation/Instrumenter.cs:line 124
   at MiniCover.Core.Instrumentation.Instrumenter.Instrument(IInstrumentationContext context) in /src/MiniCover.Core/Instrumentation/Instrumenter.cs:line 58
   at MiniCover.Commands.InstrumentCommand.Execute() in /src/MiniCover/CommandLine/Commands/InstrumentCommand.cs:line 100
   at MiniCover.Program.<>c__DisplayClass0_2.<Main>b__3() in /src/MiniCover/Program.cs:line 51
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.<>c__DisplayClass79_0.<OnExecute>b__0()
   at Microsoft.Extensions.CommandLineUtils.CommandLineApplication.Execute(String[] args)
   at MiniCover.Program.Main(String[] args) in /src/MiniCover/Program.cs:line 73`

This is not a frequently reproducible problem.
I use the last version of minicover lib -` v3.6.2`.
I tried to execute minicover instrument on the Windows OS and Linux (in docker) - results are the same.

I execute the command with the following arguments:
```
dotnet minicover instrument \
	--exclude-sources **/bin/**/*.cs \
	--exclude-sources **/obj/**/*.cs \
	--exclude-sources "**/Model/**/**/**.cs" \
	--exclude-sources **/Migrations/*.cs
```

**Comment by lucaslorentz** [comment]
It got solved by updating mono cecil I think. Diff 176

**Comment by netwer** [comment]
@lucaslorentz thank you for providing the new version with fix!

but, as far as I see the problem still reproduce:
I tried with new version (3.8.0) and got the same error:

`
Unhandled exception: System.IO.IOException: The process cannot access the file 'My.dll' because it is being used by another process.
at System.IO.FileSystem.CopyFile(String sourceFullPath, String destFullPath, Boolean overwrite)
at System.IO.Abstractions.FileWrapper.Copy(String sourceFileName, String destFileName, Boolean overwrite)
at MiniCover.Core.Instrumentation.Instrumenter.VisitAssemblyGroup(IInstrumentationContext context, InstrumentationResult result, IReadOnlyCollection1 assemblyFiles) in /home/vsts/work/1/s/src/MiniCover.Core/Instrumentation/Instrumenter.cs:line 124
at MiniCover.Core.Instrumentation.Instrumenter.Instrument(IInstrumentationContext context) in /home/vsts/work/1/s/src/MiniCover.Core/Instrumentation/Instrumenter.cs:line 58
at MiniCover.Commands.InstrumentCommand.Execute() in /home/vsts/work/1/s/src/MiniCover/CommandLine/Commands/InstrumentCommand.cs:line 100
at MiniCover.Program.<>c__DisplayClass0_0.<Main>b__0(InvocationContext context) in /home/vsts/work/1/s/src/MiniCover/Program.cs:line 56
at System.CommandLine.Invocation.AnonymousCommandHandler.InvokeAsync(InvocationContext context)
at System.CommandLine.Invocation.InvocationPipeline.<>c__DisplayClass4_0.<<BuildInvocationChain>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass17_0.<<UseParseErrorReporting>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass12_0.<<UseHelp>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass22_0.<<UseVersionOption>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass19_0.<<UseTypoCorrections>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<UseSuggestDirective>b__18_0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass16_0.<<UseParseDirective>b__0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c.<<RegisterWithDotnetSuggest>b__5_0>d.MoveNext()
--- End of stack trace from previous location ---
at System.CommandLine.Builder.CommandLineBuilderExtensions.<>c__DisplayClass8_0.<<UseExceptionHandler>b__0>d.MoveNext()
`

According to the stack trace, the problem occurs when trying to copy:
https://github.com/lucaslorentz/minicover/blob/master/src/MiniCover.Core/Instrumentation/Instrumenter.cs#L124

**Comment by lucaslorentz** [comment]
@netwer Would you please try again with v3.8.1 to confirm the fix?

**Comment by netwer** [comment]
@lucaslorentz yes, sure.
I will check and back with results.
Thanks.

**Comment by netwer** [comment]
@lucaslorentz it seems the problem was fixed by last update.
my checks was successful.
thx!
